"""alter table jobs

Revision ID: 7ecee6560e1e
Revises: d1fda1f9fee7
Create Date: 2022-01-16 14:54:49.138114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecee6560e1e'
down_revision = 'd1fda1f9fee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('working_hours', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'working_hours')
    # ### end Alembic commands ###
