"""Alter table jobs

Revision ID: a07142aa5b6a
Revises: 10d3d01e4def
Create Date: 2022-01-11 13:13:16.380219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07142aa5b6a'
down_revision = '10d3d01e4def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'created_at')
    # ### end Alembic commands ###
