"""Add Foreign Key Table jobs

Revision ID: c669cfc851b8
Revises: 5062f2bcb1ab
Create Date: 2022-01-11 22:10:44.548021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c669cfc851b8'
down_revision = '5062f2bcb1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('recruiter_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'jobs', 'recruiters', ['recruiter_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'recruiter_id')
    # ### end Alembic commands ###
