"""alter table applications

Revision ID: d1fda1f9fee7
Revises: c669cfc851b8
Create Date: 2022-01-12 08:43:38.413398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fda1f9fee7'
down_revision = 'c669cfc851b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'created_at')
    # ### end Alembic commands ###
